// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcEX0JtyhDnUPAa36QuqfAVR3E7Wr__Is',
    appId: '1:756171113352:web:dd0b384ac8169cbcb3f03d',
    messagingSenderId: '756171113352',
    projectId: 'pawscope-3b1be',
    authDomain: 'pawscope-3b1be.firebaseapp.com',
    storageBucket: 'pawscope-3b1be.firebasestorage.app',
    measurementId: 'G-7EJHEPD443',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCggfF-OW2QRS_8KROohT-DuF_SrSpCaBA',
    appId: '1:756171113352:android:0c6d93cd8a3353dcb3f03d',
    messagingSenderId: '756171113352',
    projectId: 'pawscope-3b1be',
    storageBucket: 'pawscope-3b1be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRk7bhyk1-B2ntAGygUS4F25ab8pfJOns',
    appId: '1:756171113352:ios:8a5476f939f25479b3f03d',
    messagingSenderId: '756171113352',
    projectId: 'pawscope-3b1be',
    storageBucket: 'pawscope-3b1be.firebasestorage.app',
    iosBundleId: 'com.tychew.pawscope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRk7bhyk1-B2ntAGygUS4F25ab8pfJOns',
    appId: '1:756171113352:ios:ef086cbb2c54587db3f03d',
    messagingSenderId: '756171113352',
    projectId: 'pawscope-3b1be',
    storageBucket: 'pawscope-3b1be.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcEX0JtyhDnUPAa36QuqfAVR3E7Wr__Is',
    appId: '1:756171113352:web:05940b40e83daad6b3f03d',
    messagingSenderId: '756171113352',
    projectId: 'pawscope-3b1be',
    authDomain: 'pawscope-3b1be.firebaseapp.com',
    storageBucket: 'pawscope-3b1be.firebasestorage.app',
    measurementId: 'G-452WDBWRFW',
  );
}
